[parachain]
name = "ISS Node"
description = "ISS Tracking Node"
version = "v0.2.0"

[chainspec]
version = "0.0.1"
path = "akropolis.spec"

[node]
telemetry-url = "wss://telemetry.polkadot.io/submit/"
listen-addr = "/ip4/0.0.0.0/tcp/30333"
